// Generated by CoffeeScript 1.3.3
(function() {

  CodeMirror.defineMode("apl", function(config, parserConfig) {
    var builtins, wordRE;
    wordRE = function(words) {
      return new RegExp("^(?:" + (words.join("|")) + ")$", "i");
    };
    builtins = "+ − × ÷ ⋆ ○ ?∈ ⌈ ⌊ ⍴".split(" ");
    return {
      startState: function() {
        return {
          indentStack: null,
          indentation: 0,
          mode: false
        };
      },
      token: function(stream, state) {
        var style, word;
        style = state.cur(stream, state);
        word = stream.current();
        if (builtins.test(word)) {
          style = "keyword";
        }
        return style;
      },
      indent: function(state) {
        return state.indentStack.indentation;
      }
    };
  });

  CodeMirror.defineMIME("text/x-apl", "apl");

}).call(this);
